sudo: required
services:
  - docker
language: java:8.0
jdk: openjdk8

#before_install:
 # - docker build -t amit2328/web .

script:
  - mvn clean package

after_success:
  - docker build -t amit2328/web .
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push amit2328/web

deploy:
  provider: elasticbeanstalk
  region: ap-south-1
  app: Docker
  env: Docker-env
  bucket_name: elasticbeanstalk-ap-south-1-671141137976
  bucket_path: Docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY